steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/panprices/test-crawlee', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/panprices/test-crawlee']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
      - run
      - deploy
      - test-crawlee
      - --image
      - gcr.io/panprices/test-crawlee
      - --region
      - europe-west1
      - --platform
      - managed
      - --memory=2Gi
      - --concurrency=1
      - --timeout=600s
images:
- gcr.io/panprices/test-crawlee