apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-crawlee
  namespace: default
  labels:
    app: test-crawlee
spec:
  template:
    metadata:
      labels:
          app: test-crawlee
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      volumes:
        - name: google-cloud-key
          secret:
            secretName: service-account-key
      containers:
      - env:
        - name: PANPRICES_ENVIRONMENT
          value: sandbox
        - name: SHELF_ANALYTICS_SCHEDULE_PRODUCT_SCRAPE_TOPIC
          value: trigger_schedule_product_scrapes
        - name: SHELF_ANALYTICS_UPDATE_PRODUCTS_TOPIC
          value: trigger_shelf_analytics_update_products
        - name: SHELF_ANALYTICS_UPDATE_POPULARITY_TOPIC
          value: trigger_shelf_analytics_update_products_popularity
        - name: CRAWLEE_AVAILABLE_MEMORY_RATIO
          value: '1'
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        image: gcr.io/panprices/test-crawlee
        name: test-crawlee
        ports:
        - containerPort: 8080
          name: http1
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
            ephemeral-storage: 4Gi
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
      serviceAccountName: crawlee-scraper
  selector:
      matchLabels:
        app: test-crawlee
